export type City = {
  id: string;
  city: string;
  country: string;
  region: string | null;
  short_description: string | null;
  latitude: number | null;
  longitude: number | null;
  avg_temp_monthly: number[] | null;
  temp_avg_norm: number | null;
  temp_max_norm: number | null;
  ideal_durations: string[] | null;
  budget_level: number | null;
  budget_level_num_norm: number | null;
  culture: number;
  culture_norm: number;
  adventure: number;
  adventure_norm: number;
  nature: number;
  nature_norm: number;
  beaches: number;
  beaches_norm: number;
  nightlife: number;
  nightlife_norm: number;
  cuisine: number;
  cuisine_norm: number;
  wellness: number;
  wellness_norm: number;
  urban: number;
  urban_norm: number;
  seclusion: number;
  seclusion_norm: number;
  created_at: string;
};

export type UserPreferences = {
  age: number;
  preferred_budget: number;
  preferred_avg_temp: number;
  culture: number;
  adventure: number;
  nature: number;
  beaches: number;
  nightlife: number;
  cuisine: number;
  wellness: number;
  urban: number;
  seclusion: number;
};

export type Trip = {
  id: string;
  user_id: string;
  trip_id: string | null;
  age: number | null;
  visited_city: string | null;
  preferred_budget: number | null;
  preferred_avg_temp: number | null;
  culture: number;
  adventure: number;
  nature: number;
  beaches: number;
  nightlife: number;
  cuisine: number;
  wellness: number;
  urban: number;
  seclusion: number;
  rating: number | null;
  created_at: string;
};
